= Container Signing & Trust
Keidrych Anton-Oates <me@keidrych.com>
:description: DockerHub provides a lesser known feature for Container Image Signing via Notary, understand the practical and suitable use-cases of this technology over standard unsigned containers.
:keywords: docker, signing, container
:toc: ~

https://www.redhat.com/en/blog/container-image-signing
https://csrc.nist.gov/CSRC/media/Publications/white-paper/2018/01/26/security-considerations-for-code-signing/final/documents/security-considerations-for-code-signing.pdf
https://theupdateframework.github.io/
https://github.com/openfaas/faas-cli/issues/608
https://sathyasays.com/2019/03/12/setting-up-a-secure-docker-image-scanning-solution-with-anchore-and-drone-ci/
https://docs.docker.com/engine/security/trust/trust_key_mng/
https://github.com/goharbor/harbor/blob/master/docs/user_guide.md
https://docs.docker.com/notary/getting_started/


== Situational Awareness

Humans make the majority of their decisions based on trust. What earns our trust has the highest influence of success, the problem is that while generally we are trusting creatures there are a few outliners who seek to abuse that trust. Signing of anything is about ensuring that the person who claims to have authored it actually has.

But this is only one side of the equation. The other, after ensuring the person did what they claim to, relies on if that person is actually trustworthy.

Security & Trust is a continual discu

RedHat talks in 2016 about their approach to conainer signing.

If individual code commits are capable of being signed against a person, then shouldn't the aggregation of code be signed against a team, and each piece of the operating system signed to form a complete picture?

The aforementioned question instantly shows the challenges in sucessful signing. The very concept requires that everything be atomically signed so the aggregated piece can be signed. Granted some Linux systems are trying to move this way, but only for core functionality as the thousands of individual components of often unsigned or haven't needed to be updated as they are trusted for years.

Containers being operating systems running within a host operating system introduce an interesting complexity to the equation. As they are a snapshot in time, can't we just sign this snapshot as secure and move on. Unfortunately not, as again all parts of the tree assembling the container may not be signed, or trusted. This doesn't mean we shouldn't sign containers, just to understand we cannot assume just because something is signed it should be trusted. xref:containers/cerfification.adoc[Container Certificaton] exists for the very reason of building trust that the image is safe.

== Approach to Signing Containers

Signing Containers, or what is also called _Content Trust_ is not supported by all Container Image Repositories, and for good reason. Its hard to implement with the only successful trust implementation being <<Notary Survival Guide>> via _The Update Framework_. Its also risky. Root keys must be generated, and repository independent keys and user delegations managed carefully. A mistake, and Notary will lock out the repository name from trust.

There's also the small matter of _hashing_. Most humans are comfortable grabbing the latest image via a known standard such as https://semver.org/[SemVer] but comparing hashes for container versions against timestamps to know which is the latest is challenging and problematic for late night workers.

Finally repositories must be created and signed appropriated before images can be pushed to them (working against most CI workflows for new applications)

These risks and complexities don't offset the benefits of security or verifying the container is exactly the one you wanted. They just paint a picture as to why _Container Signing_ is slow on the uptake.

The final influencing factor is the generic assumption that all containers are the same, or built with a common purpose. In point of fact, they aren't. While the vast majority of containers are built for applications, Many exist as supporting Operating System Services.

=== Application vs Operating System Containers

- **Application Containers**: are what developers are familiar with, write some code following a (hopefully) MicroService specification, push it through a Continous Integration (CI) pipeline and bundle into a Container that will run anywhere.
- **Operating System Containers**: provide dedicated services for assembling a Host Operating System to run, well, containers. https://github.com/linuxkit/linuxkit[LinuxKit] is an excellent example of using Operating System Containers.

There's a significant degree of trust difference between the two situations. While Applications are assumed and often verified as secure and safe, Operating Systems are **expected** to be safe and trusted.

=== When to Sign Containers

Spefically when used in the assembly of Operating Systems, for all other situations Container Signing adds a lot of overhead for very little benefit over Code Signing. Again xref:containers/certification.adoc[Container Certification] should be pursued instead of Signing for Application Containers to promote trust and safety in images.

=== Supporting Services

- https://goharbor.io/docs/[Harbor]: self hosted, Kubernetes compatible solution
- https://hub.docker.com/[DockerHub]: cloud based, largest container repository in existance

== Notary Survival Guide

****
**Definition**: Notary is a tool for publishing and managing trusted collections of content. Publishers can digitally sign collections and consumers can verify integrity and origin of content. This ability is built on a straightforward key management and signing interface to create signed collections and configure trusted publishers.

With Notary anyone can provide trust over arbitrary collections of data. Using The Update Framework (TUF) as the underlying security framework, Notary takes care of the operations necessary to create, manage, and distribute the metadata necessary to ensure the integrity and freshness of your content. https://docs.docker.com/notary/getting_started/[Docker's Notary Explanation]
****

```sh

```
